package com.oj.linglian.dao;

import java.util.List;

import com.oj.linglian.entity.Answer;

public interface IAnswerDao {
    public int update(Answer answer, Answer keyAnswer);
    public int updateOfAnswerId(Answer answer, String answerId);
    public int updateOfUserId(Answer answer, String userId);
    public int updateOfQuestionId(Answer answer, String questionId);
    public int updateOfBody(Answer answer, String body);
    public int updateOfTime(Answer answer, String time);
    public int updateOfAnswerIdAndUserId(Answer answer, String answerId, String userId);
    public int updateOfAnswerIdAndQuestionId(Answer answer, String answerId, String questionId);
    public int updateOfAnswerIdAndBody(Answer answer, String answerId, String body);
    public int updateOfAnswerIdAndTime(Answer answer, String answerId, String time);
    public int updateOfUserIdAndQuestionId(Answer answer, String userId, String questionId);
    public int updateOfUserIdAndBody(Answer answer, String userId, String body);
    public int updateOfUserIdAndTime(Answer answer, String userId, String time);
    public int updateOfQuestionIdAndBody(Answer answer, String questionId, String body);
    public int updateOfQuestionIdAndTime(Answer answer, String questionId, String time);
    public int updateOfBodyAndTime(Answer answer, String body, String time);
    public int remove(Answer answer);
    public int removeOfAnswerId(String answerId);
    public int removeOfUserId(String userId);
    public int removeOfQuestionId(String questionId);
    public int removeOfBody(String body);
    public int removeOfTime(String time);
    public int removeOfAnswerIdAndUserId(String answerId, String userId);
    public int removeOfAnswerIdAndQuestionId(String answerId, String questionId);
    public int removeOfAnswerIdAndBody(String answerId, String body);
    public int removeOfAnswerIdAndTime(String answerId, String time);
    public int removeOfUserIdAndQuestionId(String userId, String questionId);
    public int removeOfUserIdAndBody(String userId, String body);
    public int removeOfUserIdAndTime(String userId, String time);
    public int removeOfQuestionIdAndBody(String questionId, String body);
    public int removeOfQuestionIdAndTime(String questionId, String time);
    public int removeOfBodyAndTime(String body, String time);
    public int insert(Answer answer);
    public int insertOfAnswerId(String answerId);
    public int insertOfUserId(String userId);
    public int insertOfQuestionId(String questionId);
    public int insertOfBody(String body);
    public int insertOfTime(String time);
    public int insertOfAnswerIdAndUserId(String answerId, String userId);
    public int insertOfAnswerIdAndQuestionId(String answerId, String questionId);
    public int insertOfAnswerIdAndBody(String answerId, String body);
    public int insertOfAnswerIdAndTime(String answerId, String time);
    public int insertOfUserIdAndQuestionId(String userId, String questionId);
    public int insertOfUserIdAndBody(String userId, String body);
    public int insertOfUserIdAndTime(String userId, String time);
    public int insertOfQuestionIdAndBody(String questionId, String body);
    public int insertOfQuestionIdAndTime(String questionId, String time);
    public int insertOfBodyAndTime(String body, String time);
    public Answer getAnswer(Answer answer);
    public Answer getAnswerOfAnswerId(String answerId);
    public Answer getAnswerOfUserId(String userId);
    public Answer getAnswerOfQuestionId(String questionId);
    public Answer getAnswerOfBody(String body);
    public Answer getAnswerOfTime(String time);
    public Answer getAnswerOfAnswerIdAndUserId(String answerId, String userId);
    public Answer getAnswerOfAnswerIdAndQuestionId(String answerId, String questionId);
    public Answer getAnswerOfAnswerIdAndBody(String answerId, String body);
    public Answer getAnswerOfAnswerIdAndTime(String answerId, String time);
    public Answer getAnswerOfUserIdAndQuestionId(String userId, String questionId);
    public Answer getAnswerOfUserIdAndBody(String userId, String body);
    public Answer getAnswerOfUserIdAndTime(String userId, String time);
    public Answer getAnswerOfQuestionIdAndBody(String questionId, String body);
    public Answer getAnswerOfQuestionIdAndTime(String questionId, String time);
    public Answer getAnswerOfBodyAndTime(String body, String time);
    public List<Answer> getAnswers(Answer answer);
    public List<Answer> getAnswersOfAnswerId(String answerId);
    public List<Answer> getAnswersOfUserId(String userId);
    public List<Answer> getAnswersOfQuestionId(String questionId);
    public List<Answer> getAnswersOfBody(String body);
    public List<Answer> getAnswersOfTime(String time);
    public List<Answer> getAnswersOfAnswerIdAndUserId(String answerId, String userId);
    public List<Answer> getAnswersOfAnswerIdAndQuestionId(String answerId, String questionId);
    public List<Answer> getAnswersOfAnswerIdAndBody(String answerId, String body);
    public List<Answer> getAnswersOfAnswerIdAndTime(String answerId, String time);
    public List<Answer> getAnswersOfUserIdAndQuestionId(String userId, String questionId);
    public List<Answer> getAnswersOfUserIdAndBody(String userId, String body);
    public List<Answer> getAnswersOfUserIdAndTime(String userId, String time);
    public List<Answer> getAnswersOfQuestionIdAndBody(String questionId, String body);
    public List<Answer> getAnswersOfQuestionIdAndTime(String questionId, String time);
    public List<Answer> getAnswersOfBodyAndTime(String body, String time);
}
