package com.oj.linglian.dao;

import java.util.List;

import com.oj.linglian.entity.Comment;

public interface ICommentDao {
    public int update(Comment comment, Comment keyComment);
    public int updateOfCommentId(Comment comment, String commentId);
    public int updateOfQuestionId(Comment comment, String questionId);
    public int updateOfCoderId(Comment comment, String coderId);
    public int updateOfBody(Comment comment, String body);
    public int updateOfTime(Comment comment, String time);
    public int updateOfUserId(Comment comment, String userId);
    public int updateOfCommentIdAndQuestionId(Comment comment, String commentId, String questionId);
    public int updateOfCommentIdAndCoderId(Comment comment, String commentId, String coderId);
    public int updateOfCommentIdAndBody(Comment comment, String commentId, String body);
    public int updateOfCommentIdAndTime(Comment comment, String commentId, String time);
    public int updateOfCommentIdAndUserId(Comment comment, String commentId, String userId);
    public int updateOfQuestionIdAndCoderId(Comment comment, String questionId, String coderId);
    public int updateOfQuestionIdAndBody(Comment comment, String questionId, String body);
    public int updateOfQuestionIdAndTime(Comment comment, String questionId, String time);
    public int updateOfQuestionIdAndUserId(Comment comment, String questionId, String userId);
    public int updateOfCoderIdAndBody(Comment comment, String coderId, String body);
    public int updateOfCoderIdAndTime(Comment comment, String coderId, String time);
    public int updateOfCoderIdAndUserId(Comment comment, String coderId, String userId);
    public int updateOfBodyAndTime(Comment comment, String body, String time);
    public int updateOfBodyAndUserId(Comment comment, String body, String userId);
    public int updateOfTimeAndUserId(Comment comment, String time, String userId);
    public int remove(Comment comment);
    public int removeOfCommentId(String commentId);
    public int removeOfQuestionId(String questionId);
    public int removeOfCoderId(String coderId);
    public int removeOfBody(String body);
    public int removeOfTime(String time);
    public int removeOfUserId(String userId);
    public int removeOfCommentIdAndQuestionId(String commentId, String questionId);
    public int removeOfCommentIdAndCoderId(String commentId, String coderId);
    public int removeOfCommentIdAndBody(String commentId, String body);
    public int removeOfCommentIdAndTime(String commentId, String time);
    public int removeOfCommentIdAndUserId(String commentId, String userId);
    public int removeOfQuestionIdAndCoderId(String questionId, String coderId);
    public int removeOfQuestionIdAndBody(String questionId, String body);
    public int removeOfQuestionIdAndTime(String questionId, String time);
    public int removeOfQuestionIdAndUserId(String questionId, String userId);
    public int removeOfCoderIdAndBody(String coderId, String body);
    public int removeOfCoderIdAndTime(String coderId, String time);
    public int removeOfCoderIdAndUserId(String coderId, String userId);
    public int removeOfBodyAndTime(String body, String time);
    public int removeOfBodyAndUserId(String body, String userId);
    public int removeOfTimeAndUserId(String time, String userId);
    public int insert(Comment comment);
    public int insertOfCommentId(String commentId);
    public int insertOfQuestionId(String questionId);
    public int insertOfCoderId(String coderId);
    public int insertOfBody(String body);
    public int insertOfTime(String time);
    public int insertOfUserId(String userId);
    public int insertOfCommentIdAndQuestionId(String commentId, String questionId);
    public int insertOfCommentIdAndCoderId(String commentId, String coderId);
    public int insertOfCommentIdAndBody(String commentId, String body);
    public int insertOfCommentIdAndTime(String commentId, String time);
    public int insertOfCommentIdAndUserId(String commentId, String userId);
    public int insertOfQuestionIdAndCoderId(String questionId, String coderId);
    public int insertOfQuestionIdAndBody(String questionId, String body);
    public int insertOfQuestionIdAndTime(String questionId, String time);
    public int insertOfQuestionIdAndUserId(String questionId, String userId);
    public int insertOfCoderIdAndBody(String coderId, String body);
    public int insertOfCoderIdAndTime(String coderId, String time);
    public int insertOfCoderIdAndUserId(String coderId, String userId);
    public int insertOfBodyAndTime(String body, String time);
    public int insertOfBodyAndUserId(String body, String userId);
    public int insertOfTimeAndUserId(String time, String userId);
    public Comment getComment(Comment comment);
    public Comment getCommentOfCommentId(String commentId);
    public Comment getCommentOfQuestionId(String questionId);
    public Comment getCommentOfCoderId(String coderId);
    public Comment getCommentOfBody(String body);
    public Comment getCommentOfTime(String time);
    public Comment getCommentOfUserId(String userId);
    public Comment getCommentOfCommentIdAndQuestionId(String commentId, String questionId);
    public Comment getCommentOfCommentIdAndCoderId(String commentId, String coderId);
    public Comment getCommentOfCommentIdAndBody(String commentId, String body);
    public Comment getCommentOfCommentIdAndTime(String commentId, String time);
    public Comment getCommentOfCommentIdAndUserId(String commentId, String userId);
    public Comment getCommentOfQuestionIdAndCoderId(String questionId, String coderId);
    public Comment getCommentOfQuestionIdAndBody(String questionId, String body);
    public Comment getCommentOfQuestionIdAndTime(String questionId, String time);
    public Comment getCommentOfQuestionIdAndUserId(String questionId, String userId);
    public Comment getCommentOfCoderIdAndBody(String coderId, String body);
    public Comment getCommentOfCoderIdAndTime(String coderId, String time);
    public Comment getCommentOfCoderIdAndUserId(String coderId, String userId);
    public Comment getCommentOfBodyAndTime(String body, String time);
    public Comment getCommentOfBodyAndUserId(String body, String userId);
    public Comment getCommentOfTimeAndUserId(String time, String userId);
    public List<Comment> getComments(Comment comment);
    public List<Comment> getCommentsOfCommentId(String commentId);
    public List<Comment> getCommentsOfQuestionId(String questionId);
    public List<Comment> getCommentsOfCoderId(String coderId);
    public List<Comment> getCommentsOfBody(String body);
    public List<Comment> getCommentsOfTime(String time);
    public List<Comment> getCommentsOfUserId(String userId);
    public List<Comment> getCommentsOfCommentIdAndQuestionId(String commentId, String questionId);
    public List<Comment> getCommentsOfCommentIdAndCoderId(String commentId, String coderId);
    public List<Comment> getCommentsOfCommentIdAndBody(String commentId, String body);
    public List<Comment> getCommentsOfCommentIdAndTime(String commentId, String time);
    public List<Comment> getCommentsOfCommentIdAndUserId(String commentId, String userId);
    public List<Comment> getCommentsOfQuestionIdAndCoderId(String questionId, String coderId);
    public List<Comment> getCommentsOfQuestionIdAndBody(String questionId, String body);
    public List<Comment> getCommentsOfQuestionIdAndTime(String questionId, String time);
    public List<Comment> getCommentsOfQuestionIdAndUserId(String questionId, String userId);
    public List<Comment> getCommentsOfCoderIdAndBody(String coderId, String body);
    public List<Comment> getCommentsOfCoderIdAndTime(String coderId, String time);
    public List<Comment> getCommentsOfCoderIdAndUserId(String coderId, String userId);
    public List<Comment> getCommentsOfBodyAndTime(String body, String time);
    public List<Comment> getCommentsOfBodyAndUserId(String body, String userId);
    public List<Comment> getCommentsOfTimeAndUserId(String time, String userId);
}
